import os
import shutil
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Styling
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['font.sans-serif'] = 'Helvetica, Arial, sans-serif'
plt.rcParams['axes.edgecolor'] = '#cbd5e1'
plt.rcParams['axes.linewidth'] = 0.8

output_dir = r"c:\Users\admir\Github\computational-sketchbook\2026\2026-09-26-education-data-observatory\dashboard"
artifact_dir = r"C:\Users\admir\.gemini\antigravity\brain\341419bd-5669-4622-8d51-d6eecec301ff"
os.makedirs(output_dir, exist_ok=True)

# Data paths
kc_school_path = r"2026/2026-09-23-kc-education-capacity/data/processed/kc_school_capacity_2024_2025.csv"
kc_lea_path = r"2026/2026-09-23-kc-education-capacity/data/processed/kc_lea_capacity_2024_2025.csv"
lea_long_path = r"2026/2026-09-23-kc-education-capacity/data/processed/kc_lea_capacity_long_2014_15_2024_25.csv"

sch_df = pd.read_csv(kc_school_path)
lea_df = pd.read_csv(kc_lea_path)
lea_long = pd.read_csv(lea_long_path)

# -------------------------------------------------------------
# FIGURE 4: DESCRIPTIVE OBSERVATION
# School Size Distribution by Grade Level in KC Metro (SY 2024-25)
# -------------------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 5.5), dpi=300)

levels = ['Elementary', 'Middle', 'High', 'Prekindergarten']
data_by_level = []
level_labels = []

for lvl in levels:
    vals = sch_df[(sch_df['school_level'] == lvl) & (sch_df['enrollment_total'] > 0)]['enrollment_total'].dropna().values
    data_by_level.append(vals)
    med = np.median(vals)
    mean = np.mean(vals)
    level_labels.append(f"{lvl}\n(N={len(vals)})\nMed: {med:.0f} | Mean: {mean:.0f}")

box = ax.boxplot(data_by_level, tick_labels=level_labels, patch_artist=True,
                 boxprops=dict(facecolor='#e0f2fe', edgecolor='#0284c7', linewidth=1.2),
                 medianprops=dict(color='#0369a1', linewidth=2),
                 whiskerprops=dict(color='#0284c7', linewidth=1),
                 capprops=dict(color='#0284c7', linewidth=1),
                 flierprops=dict(marker='o', markersize=4, markerfacecolor='#f43f5e', markeredgecolor='none', alpha=0.6))

# Annotate extreme outliers
ax.annotate('Mega Suburban High Schools\n(Blue Springs: 2,429; Liberty North: 2,262)',
            xy=(3, 2429), xytext=(3.25, 2100),
            arrowprops=dict(arrowstyle="->", color='#e11d48', lw=1),
            fontsize=8.5, fontweight='bold', color='#be123c')

ax.annotate('Dedicated Early Childhood Centers\n(Grace: 228; Shull: 189)',
            xy=(4, 228), xytext=(3.3, 500),
            arrowprops=dict(arrowstyle="->", color='#0369a1', lw=1),
            fontsize=8.5, fontweight='bold', color='#0369a1')

ax.set_ylabel('Total Enrolled Students (Fall Headcount MEMBER)', fontsize=10.5, fontweight='semibold')
ax.set_title('[DESCRIPTIVE OBSERVATION] Campus Institutional Scale: School Size Distributions by Grade Band\n691 Operating Public Schools Across 9-County Kansas City Metropolitan Area (SY 2024–25)', fontsize=11, fontweight='bold', pad=15)
ax.set_ylim(0, 2600)

footer_text4 = (
    "CLASSIFICATION: DESCRIPTIVE OBSERVATION. Source: NCES CCD Public School Universe Directory File (SY 2024–25).\n"
    "Population: Operating public schools in 9 MARC counties (MO & KS). Excludes 26 vocational/alternative schools reporting 0 primary enrollment.\n"
    "Generated by: analysis/cross-measure/generate_edu002_visuals.py"
)
plt.figtext(0.5, 0.01, footer_text4, ha="center", fontsize=7.5, color="#475569",
             bbox=dict(boxstyle="round,pad=0.4", facecolor="#f8fafc", edgecolor="#cbd5e1", alpha=0.9))

plt.subplots_adjust(top=0.88, bottom=0.18)
fig4_path = os.path.join(output_dir, "fig04_school_size_distribution.png")
plt.savefig(fig4_path)
plt.close()
shutil.copy(fig4_path, os.path.join(artifact_dir, "fig04_school_size_distribution.png"))

# -------------------------------------------------------------
# FIGURE 5: DESCRIPTIVE OBSERVATION
# The Campus vs. LEA Aggregation Discrepancy
# -------------------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 5.2), dpi=300)

sch_by_lea = sch_df.groupby('nces_lea_id')['enrollment_total'].sum().reset_index(name='campus_sum_enrollment')
merged_lea = pd.merge(lea_df[['nces_lea_id', 'district_name', 'state', 'enrollment_total']], sch_by_lea, on='nces_lea_id', how='left')
merged_lea['diff'] = merged_lea['enrollment_total'] - merged_lea['campus_sum_enrollment'].fillna(0)

# Top 8 LEAs with positive unassigned students
top_diff = merged_lea.sort_values(by='diff', ascending=False).head(8)

y_pos = np.arange(len(top_diff))
bars = ax.barh(y_pos, top_diff['diff'], color='#3b82f6', height=0.55, edgecolor='#1d4ed8')

ax.set_yticks(y_pos)
ax.set_yticklabels(top_diff['district_name'] + " (" + top_diff['state'] + ")", fontsize=9.5)
ax.invert_yaxis()

for bar, d, tot in zip(bars, top_diff['diff'], top_diff['enrollment_total']):
    pct = d / tot * 100
    ax.text(d + 12, bar.get_y() + bar.get_height()/2,
            f"+{d:,.0f} unassigned students ({pct:.1f}% of district)",
            va='center', ha='left', fontsize=8.5, fontweight='bold', color='#1e293b')

ax.set_xlabel('Unassigned Students: LEA Total Enrollment Minus Sum of Campus Enrollments', fontsize=10, fontweight='semibold')
ax.set_title('[DESCRIPTIVE OBSERVATION] The LEA–School Membership Reconciliation Gap: Where Are the Students?\nTop Kansas City Districts Where LEA Membership Exceeds the Sum of Physical School Rosters (SY 2024–25)', fontsize=10.5, fontweight='bold', pad=15)
ax.set_xlim(0, 850)

footer_text5 = (
    "CLASSIFICATION: DESCRIPTIVE OBSERVATION. Source: NCES CCD LEA Survey vs. School Universe Survey (SY 2024–25).\n"
    "Reconciliation gaps occur when students are placed in out-of-district day schools, homebound programs, or central administrative rolls without a building code.\n"
    "Total regional discrepancy across all 77 MARC districts: +2,445 students. Generated by: analysis/cross-measure/generate_edu002_visuals.py"
)
plt.figtext(0.5, 0.015, footer_text5, ha="center", fontsize=7.5, color="#475569",
             bbox=dict(boxstyle="round,pad=0.4", facecolor="#f8fafc", edgecolor="#cbd5e1", alpha=0.9))

plt.subplots_adjust(left=0.28, bottom=0.18, right=0.90, top=0.86)
fig5_path = os.path.join(output_dir, "fig05_campus_vs_lea_enrollment_gap.png")
plt.savefig(fig5_path)
plt.close()
shutil.copy(fig5_path, os.path.join(artifact_dir, "fig05_campus_vs_lea_enrollment_gap.png"))

# -------------------------------------------------------------
# FIGURE 6: DESCRIPTIVE OBSERVATION
# 11-Year Longitudinal Trajectory: The Fall 2020 Drop & Stagnation
# -------------------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 5.2), dpi=300)

yearly_enr = lea_long.groupby('school_year')['enrollment_k12'].sum().reset_index()
years = yearly_enr['school_year'].values
counts = yearly_enr['enrollment_k12'].values

ax.plot(years, counts, marker='o', color='#0284c7', linewidth=2.5, markersize=6, label='Regional K–12 Membership')
ax.fill_between(years, counts, color='#0284c7', alpha=0.08)

# Highlight pre-COVID peak and drop
peak_idx = 5 # 2019-20
covid_idx = 6 # 2020-21
drop = counts[covid_idx] - counts[peak_idx]

ax.scatter([years[peak_idx]], [counts[peak_idx]], color='#10b981', s=80, zorder=5)
ax.scatter([years[covid_idx]], [counts[covid_idx]], color='#ef4444', s=80, zorder=5)

ax.annotate(f"Pre-Pandemic Peak\n({counts[peak_idx]:,})",
            xy=(years[peak_idx], counts[peak_idx]), xytext=(-40, 20),
            textcoords="offset points", fontsize=8.5, fontweight='bold', color='#065f46',
            arrowprops=dict(arrowstyle="->", color='#059669'))

ax.annotate(f"Fall 2020 Drop: {drop:,.0f} students (-2.2%)\nPost-2020 enrollment stagnates at ~320k",
            xy=(years[covid_idx], counts[covid_idx]), xytext=(20, -35),
            textcoords="offset points", fontsize=8.5, fontweight='bold', color='#991b1b',
            arrowprops=dict(arrowstyle="->", color='#dc2626'))

ax.set_ylabel('Total K–12 Headcount Enrollment', fontsize=10.5, fontweight='semibold')
ax.set_title('[DESCRIPTIVE OBSERVATION] 11-Year Regional Enrollment Trajectory: The Fall 2020 Drop & Stagnation\n77 Operating School Districts Across 9-County KC Metro (SY 2014–15 to SY 2024–25)', fontsize=11, fontweight='bold', pad=15)
ax.set_ylim(310000, 335000)
ax.set_xticks(years)
ax.set_xticklabels(years, rotation=35, ha='right', fontsize=9)

footer_text6 = (
    "CLASSIFICATION: DESCRIPTIVE OBSERVATION. Source: Audited 11-Year NCES CCD LEA Longitudinal Panel (SY 2014–15 through SY 2024–25).\n"
    "Shows K–12 enrollment excluding Pre-K. Regional enrollment peaked at 330,128 in 2019–20 before falling to 320,031 in 2024–25 (-3.06% from peak).\n"
    "Generated by: analysis/cross-measure/generate_edu002_visuals.py"
)
plt.figtext(0.5, 0.015, footer_text6, ha="center", fontsize=7.5, color="#475569",
             bbox=dict(boxstyle="round,pad=0.4", facecolor="#f8fafc", edgecolor="#cbd5e1", alpha=0.9))

plt.subplots_adjust(bottom=0.20, top=0.88)
fig6_path = os.path.join(output_dir, "fig06_longitudinal_enrollment_trajectory.png")
plt.savefig(fig6_path)
plt.close()
shutil.copy(fig6_path, os.path.join(artifact_dir, "fig06_longitudinal_enrollment_trajectory.png"))

print("All 3 EDU-002 figures successfully created and copied to artifacts directory!")
