"""Unit tests for CADO-NFS file and stdout parsers."""

import pytest
from nsb.baselines.cado_nfs.parser import (
    parse_cado_poly_file,
    parse_cado_score_output,
    parse_las_output,
)


def test_parse_cado_poly_file():
    poly_text = """
    # CADO-NFS polynomial selection output
    # Generated by polyselect
    n: 903776292920031201
    skew: 2.3456
    c0: -1234567
    c1: 456789
    c2: -1234
    c3: 56
    c4: -2
    c5: 1
    Y0: -789012
    Y1: 1
    # m: 789012
    # author: cado
    """
    pair = parse_cado_poly_file(poly_text)
    assert pair.N == 903776292920031201
    assert abs(pair.skew - 2.3456) < 1e-4
    assert pair.degree1 == 5
    assert pair.degree2 == 1
    assert pair.f1_coeffs == [-1234567, 456789, -1234, 56, -2, 1]
    assert pair.f2_coeffs == [-789012, 1]
    assert pair.m == 789012
    assert pair.metadata.get("author") == "cado"


def test_parse_cado_poly_file_root_derivation():
    # If m is not explicitly in comments, but Y1*m + Y0 = 0 (mod N)
    poly_text = """
    n: 10007
    skew: 1.0
    c0: -1
    c1: 1
    Y0: -500
    Y1: 1
    """
    pair = parse_cado_poly_file(poly_text)
    assert pair.m == 500


def test_parse_cado_poly_file_invalid():
    # Missing coefficients
    poly_text = """
    n: 10007
    skew: 1.0
    """
    with pytest.raises(ValueError):
        parse_cado_poly_file(poly_text)


def test_parse_cado_score_output_standard():
    score_out = """
    # Evaluation of polynomial
    skew = 2.45
    lognorm = 48.72
    alpha = -2.18
    exp_E = 46.54
    MurphyE(exp_E=46.54,alpha=-2.18) = 3.4567e-11
    """
    res = parse_cado_score_output(score_out)
    assert abs(res.murphy_e - 3.4567e-11) < 1e-15
    assert abs(res.lognorm - 48.72) < 1e-3
    assert abs(res.alpha - (-2.18)) < 1e-3
    assert abs(res.skew - 2.45) < 1e-3


def test_parse_cado_score_output_alternative():
    score_out = """
    Murphy-E: 1.25e-10
    alpha: -3.42
    exp_E: 52.1
    """
    res = parse_cado_score_output(score_out)
    assert abs(res.murphy_e - 1.25e-10) < 1e-14
    assert abs(res.alpha - (-3.42)) < 1e-3
    assert abs(res.lognorm - 52.1) < 1e-3


def test_parse_cado_score_output_missing():
    score_out = "Error: polynomial could not be loaded."
    with pytest.raises(ValueError):
        parse_cado_score_output(score_out)


def test_parse_cado_poly_blocks():
    multi_poly_text = """
    # Block 1
    n: 903776292920031201
    skew: 2.1
    c0: -100
    c1: 20
    c2: 3
    Y0: -50
    Y1: 1
    # MurphyE(exp_E=40.0) = 1.0e-12

    # Block 2
    n: 903776292920031201
    skew: 2.5
    c0: -200
    c1: 30
    c2: 4
    Y0: -60
    Y1: 1
    # MurphyE(exp_E=42.0) = 2.5e-12
    """
    from nsb.baselines.cado_nfs.parser import parse_cado_poly_blocks
    blocks = parse_cado_poly_blocks(multi_poly_text)
    assert len(blocks) == 2
    assert blocks[0].f1_coeffs == [-100, 20, 3]
    assert blocks[1].f1_coeffs == [-200, 30, 4]

    # parse_cado_poly_file selects candidate with higher Murphy-E
    best = parse_cado_poly_file(multi_poly_text)
    assert best.f1_coeffs == [-200, 30, 4]


def test_parse_cado_score_output_real_whitespace_format():
    score_out = """
    # exp_E  46.54, lognorm  48.72, skew  2.45, 3 rroots
    # MurphyE(Bf=1000000, Bg=500000, area=1.00e+07) = 3.4567e-11
    """
    res = parse_cado_score_output(score_out)
    assert abs(res.murphy_e - 3.4567e-11) < 1e-15
    assert abs(res.lognorm - 48.72) < 1e-3
    assert abs(res.exp_e - 46.54) < 1e-3
    assert abs(res.skew - 2.45) < 1e-3
    assert res.rroots == 3


def test_parse_las_output():
    las_out = """
    # las lattice siever output
    # special-q: 50000000..50000200
    101,23:2,3,5:7,11
    102,23:3,5,7:13,17
    101,23:2,3,5:7,11
    103,25:2,7:19,23
    # Total 4 relations
    # Total cpu time: 2.50s
    # Total elapsed time: 0.85s
    """
    res = parse_las_output(las_out)
    assert res.total_relations == 4
    # 1 duplicate in the 4 relations, so 3 unique
    assert res.unique_relations == 3
    assert res.q_start == 50000000
    assert res.q_range == 200
    assert abs(res.cpu_seconds - 2.50) < 1e-3
    assert abs(res.wall_seconds - 0.85) < 1e-3
    assert res.relations_per_cpu_second == round(3 / 2.50, 4)
    assert res.relations_hash != ""
    assert res.ab_pairs_hash != ""
    assert res.reported_relations_count == 4
    assert res.parsed_relations_count == 4
    assert res.conservation_checked is True


def test_parse_cado_poly_blocks_best_rank():
    text = """
    # 0-th best polynomial found (Murphy_E=4.12e-11):
    n: 903776292920031201
    skew: 2.1
    c0: -100
    c1: 20
    c2: 3
    Y0: -50
    Y1: 1
    # Murphy_E = 4.12e-11
    """
    from nsb.baselines.cado_nfs.parser import parse_cado_poly_blocks
    blocks = parse_cado_poly_blocks(text)
    assert len(blocks) == 1
    assert blocks[0].metadata.get("is_best") is True
    assert blocks[0].metadata.get("best_rank") == 0
    assert abs(blocks[0].metadata.get("murphy_e") - 4.12e-11) < 1e-15


def test_parse_las_output_missing_reported_count_fails_closed():
    """Fail closed when LAS output lacks the '# Total <n> reports' line under enforce_conservation=True."""
    las_out = """
    # las lattice siever output without total count line
    101,23:2,3,5:7,11
    102,23:3,5,7:13,17
    # Total cpu time: 2.50s
    """
    import pytest
    with pytest.raises(ValueError, match="missing '# Total <n> reports' summary line"):
        parse_las_output(las_out, enforce_conservation=True)

    # Without enforcement, it parses relations without failing
    res = parse_las_output(las_out, enforce_conservation=False)
    assert res.total_relations == 2
    assert res.conservation_checked is False

