"""
Generate standardized funding timelines for Center 58 and Hickman Mills C-1
based on primary IRS Form 990-PF filings (2019-2024).
"""

import csv
from pathlib import Path

BASE_DIR = Path("2026/2026-09-26-rwl-institutionalization")

CENTER_GRANTS = [
    {
        "funding_event_id": "FUND-CTR-2019-01",
        "event_date": "2019",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 64902,
        "grant_id": "201904-6355",
        "purpose": "Support the development of a three-year strategic plan to increase the number of graduates leaving high school ready for learning work and life in the Kansas City region",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "initial_design_grant",
        "district_match": "unknown",
        "closeout_end_date": "2020-06-30",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-008",
        "notes": "Direct Kauffman TY2019 Form 990-PF grant row (Filing 202003169349101105); Cohort 1 Design & Plan grant"
    },
    {
        "funding_event_id": "FUND-CTR-2020-01",
        "event_date": "2020",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 150000,
        "grant_id": "202007-8756",
        "purpose": "Support increased opportunities for students in the Kansas City region to graduate from high school prepared for learning work and life",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "implementation_phase_1",
        "district_match": "unknown",
        "closeout_end_date": "2021-06-30",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-009",
        "notes": "Direct Kauffman TY2020 Form 990-PF grant row (Filing 202143159349103869); first tranche of Implementation Phase 1"
    },
    {
        "funding_event_id": "FUND-CTR-2021-01",
        "event_date": "2021",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 150000,
        "grant_id": "202007-8756",
        "purpose": "Support increased opportunities for students in the Kansas City region to graduate from high school prepared for learning work and life",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "implementation_phase_1_continuation",
        "district_match": "unknown",
        "closeout_end_date": "2022-06-30",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-010",
        "notes": "Direct Kauffman TY2021 Form 990-PF grant row (Filing 202213189349105236); second tranche of Implementation Phase 1"
    },
    {
        "funding_event_id": "FUND-CTR-2022-01",
        "event_date": "2022",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 0,
        "grant_id": "none",
        "purpose": "No new direct RWL disbursements; expenditure of prior grant balances (district received parallel $150k equity grant 202206-12541)",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "unrestricted",
        "renewal_status": "interim_gap",
        "district_match": "unknown",
        "closeout_end_date": "unknown",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-011",
        "notes": "Direct Kauffman TY2022 Form 990-PF shows $0 paid for RWL (Grant 12541 was for equity strategic plan)"
    },
    {
        "funding_event_id": "FUND-CTR-2023-01",
        "event_date": "2023",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 135000,
        "grant_id": "202307-14163",
        "purpose": "Support for the continued implementation of a district-wide Real World Learning strategic plan to increase the number of graduates leaving high school ready for learning work and life in the Kansas City region",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "continuation_phase_2",
        "district_match": "unknown",
        "closeout_end_date": "2024-12-31",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-004",
        "notes": "Direct Kauffman TY2023 Form 990-PF grant row (Filing 202443209349101644); Line 3a paid $135k plus Line 3b approved for future $135k"
    },
    {
        "funding_event_id": "FUND-CTR-2024-01",
        "event_date": "2024",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 135000,
        "grant_id": "202307-14163",
        "purpose": "Support for the continued implementation of a district-wide Real World Learning strategic plan to increase the number of graduates leaving high school ready for learning work and life in the Kansas City region",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "continuation_phase_2_final_tranche",
        "district_match": "unknown",
        "closeout_end_date": "2024-12-31",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-006",
        "notes": "Direct Kauffman TY2024 Form 990-PF grant row (Filing 202523169349103332); final tranche of 14163 paid; Line 3b approved for future is $0"
    },
    {
        "funding_event_id": "FUND-CTR-2025-STATUS",
        "event_date": "2025-01-01",
        "date_precision": "exact",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Center School District #58",
        "recipient_type": "district",
        "amount_usd": 0,
        "grant_id": "none",
        "purpose": "Scheduled grant commitments fulfilled; Line 3b approved for future is $0 as of 2024-12-31",
        "rwl_linkage": "explicit",
        "directness": "grant_commitment_fulfilled",
        "fund_account_code": "unknown",
        "restricted_status": "unknown",
        "renewal_status": "completed_no_active_future_commitments",
        "district_match": "none",
        "closeout_end_date": "2024-12-31",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-006",
        "notes": "Primary 2024 990-PF confirms no future approved grants on foundation books; transition to post-direct-grant regime"
    }
]

HICKMAN_GRANTS = [
    {
        "funding_event_id": "FUND-HCK-2019-01",
        "event_date": "2019",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 58210,
        "grant_id": "201904-6354",
        "purpose": "Support the development of a three-year strategic plan to increase the number of graduates leaving high school ready for learning work and life in the Kansas City region",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "initial_design_grant",
        "district_match": "unknown",
        "closeout_end_date": "2020-06-30",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-008",
        "notes": "Direct Kauffman TY2019 Form 990-PF grant row (Filing 202003169349101105); Cohort 1 Design & Plan grant"
    },
    {
        "funding_event_id": "FUND-HCK-2020-01",
        "event_date": "2020",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 149817,
        "grant_id": "202007-8891",
        "purpose": "Support increased opportunities for students in the Kansas City region to graduate from high school prepared for learning work and life",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "implementation_phase_1",
        "district_match": "unknown",
        "closeout_end_date": "2021-06-30",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-009",
        "notes": "Direct Kauffman TY2020 Form 990-PF grant row (Filing 202143159349103869); first tranche of Implementation Phase 1"
    },
    {
        "funding_event_id": "FUND-HCK-2021-01",
        "event_date": "2021",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 150000,
        "grant_id": "202007-8891",
        "purpose": "Support increased opportunities for students in the Kansas City region to graduate from high school prepared for learning work and life",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "implementation_phase_1_continuation",
        "district_match": "unknown",
        "closeout_end_date": "2022-06-30",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-010",
        "notes": "Direct Kauffman TY2021 Form 990-PF grant row (Filing 202213189349105236); second tranche of Implementation Phase 1"
    },
    {
        "funding_event_id": "FUND-HCK-2022-01",
        "event_date": "2022",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 0,
        "grant_id": "none",
        "purpose": "No new direct RWL disbursements; expenditure of prior grant balances (district received parallel $150k equity grant 202206-12540)",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "unrestricted",
        "renewal_status": "interim_gap",
        "district_match": "unknown",
        "closeout_end_date": "unknown",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-011",
        "notes": "Direct Kauffman TY2022 Form 990-PF shows $0 paid for RWL (Grant 12540 was for equity strategic plan)"
    },
    {
        "funding_event_id": "FUND-HCK-2023-01",
        "event_date": "2023",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 135000,
        "grant_id": "202308-14260",
        "purpose": "Support for the continued implementation of a district-wide Real World Learning strategic plan to increase the number of graduates leaving high school ready for learning work and life in the Kansas City region",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "continuation_phase_2",
        "district_match": "unknown",
        "closeout_end_date": "2024-12-31",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-004",
        "notes": "Direct Kauffman TY2023 Form 990-PF grant row (Filing 202443209349101644); Line 3a paid $135k plus Line 3b approved for future $135k"
    },
    {
        "funding_event_id": "FUND-HCK-2024-01",
        "event_date": "2024",
        "date_precision": "tax_year",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 135000,
        "grant_id": "202308-14260",
        "purpose": "Support for the continued implementation of a district-wide Real World Learning strategic plan to increase the number of graduates leaving high school ready for learning work and life in the Kansas City region",
        "rwl_linkage": "explicit",
        "directness": "direct",
        "fund_account_code": "unknown",
        "restricted_status": "restricted",
        "renewal_status": "continuation_phase_2_final_tranche",
        "district_match": "unknown",
        "closeout_end_date": "2024-12-31",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-006",
        "notes": "Direct Kauffman TY2024 Form 990-PF grant row (Filing 202523169349103332); final tranche of 14260 paid; Line 3b approved for future is $0"
    },
    {
        "funding_event_id": "FUND-HCK-2025-STATUS",
        "event_date": "2025-01-01",
        "date_precision": "exact",
        "funder": "Ewing Marion Kauffman Foundation",
        "recipient": "Hickman Mills C-1 School District",
        "recipient_type": "district",
        "amount_usd": 0,
        "grant_id": "none",
        "purpose": "Scheduled grant commitments fulfilled; Line 3b approved for future is $0 as of 2024-12-31",
        "rwl_linkage": "explicit",
        "directness": "grant_commitment_fulfilled",
        "fund_account_code": "unknown",
        "restricted_status": "unknown",
        "renewal_status": "completed_no_active_future_commitments",
        "district_match": "none",
        "closeout_end_date": "2024-12-31",
        "confidence": "high",
        "source_id": "SRC-REG-KAUF-006",
        "notes": "Primary 2024 990-PF confirms no future approved grants on foundation books; transition to post-direct-grant regime"
    }
]

def save_timeline(grants, out_path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    headers = list(grants[0].keys())
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(grants)
    print(f"Saved {len(grants)} grant rows to {out_path}")

def build_all():
    save_timeline(CENTER_GRANTS, BASE_DIR / "districts" / "center-58" / "finance" / "center58_rwl_funding_timeline.csv")
    save_timeline(HICKMAN_GRANTS, BASE_DIR / "districts" / "hickman-mills" / "finance" / "hickmanmills_rwl_funding_timeline.csv")

if __name__ == "__main__":
    build_all()
