BEGIN;
CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS profile (id INTEGER PRIMARY KEY, display_name TEXT, timezone TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tag (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS attachment (id INTEGER PRIMARY KEY, path TEXT NOT NULL, mime TEXT, bytes INTEGER, note TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY, ts TEXT DEFAULT CURRENT_TIMESTAMP, actor TEXT, action TEXT, entity TEXT, entity_id INTEGER, note TEXT);
INSERT INTO schema_version(version, applied_at) VALUES (1, CURRENT_TIMESTAMP);
COMMIT;
